[env]
CC_riscv32im_risc0_zkvm_elf = "/root/.risc0/cpp/bin/riscv32-unknown-elf-gcc"
CFLAGS_riscv32im_risc0_zkvm_elf = "-march=rv32im -nostdlib -fno-stack-protector"
RISC0_FEATURE_bigint2 = "1"

[target."riscv32im-risc0-zkvm-elf"]
rustflags = [
  "--cfg", "getrandom_backend=\"custom\"",
  "-C", "link-arg=-march=rv32im",
  "-C", "link-arg=-mabi=ilp32",
  "-C", "link-arg=-nostartfiles",
]
