# methods/guest/.cargo/config.toml

[env]
# Use the riscv32-unknown-elf-gcc that comes preinstalled in the RISC0 Docker image
CC_riscv32im_risc0_zkvm_elf = "/root/.risc0/cpp/bin/riscv32-unknown-elf-gcc"

# Pass -DOPENSSL_32_BIT (for Ring), plus -march=rv32im
CFLAGS_riscv32im_risc0_zkvm_elf = "-march=rv32im -nostdlib -fno-stack-protector"

# Enable any RISC0 features you need (e.g. bigint2)
RISC0_FEATURE_bigint2 = "1"

[target."riscv32im-risc0-zkvm-elf"]
rustflags = [
  "--cfg", "getrandom_backend=\"custom\"",
  "-C", "link-arg=-march=rv32im",
  "-C", "link-arg=-mabi=ilp32",
  "-C", "link-arg=-nostartfiles",
]
